/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalprogrammingproject;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;

/**
 * Author: Abiishan and Munsif
 * Date: Jan. 24, 2023 
 * Project Name: frmInstructions.java
 * Description: Creating a instructions screen so that the user can learn how to play the game and know what controls to use before actually playing.
 */

public class frmInstructions extends javax.swing.JFrame {

   // Sound Effect Variables 

    public Clip music; // Represents the audio clip for background music
    public long songTime = 0; // Represents the current time position in the music playback
    
    /**
     * Creates new form frmMainMenu
     */
    public frmInstructions() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        loadMusic();
        txtAInstructions.setEditable(false);
        music.setMicrosecondPosition(songTime);// this set the song to start at the amount of time that the song has played.
        music.loop(-1);
    }

    // Loads the background music from a file
    public void loadMusic() {
        // LOADING SOUND EFFECTS
        // Source: https://opengameart.org/content/platformer-game-music-pack

        try {
            // Load the audio file into an AudioInputStream
            AudioInputStream song = AudioSystem.getAudioInputStream(new File("introMusic.wav"));

            // Initialize the music clip
            music = AudioSystem.getClip();
            music.loop(0); // This will loop forever once played
            music.open(song);

        } catch (Exception e) {
            System.out.println(e + "Song file not found");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDraw = new javax.swing.JPanel(){

            //paintComponent happens on object creation and when
            //any changes occur to the frame (size change, new objects added.
                // etc.)
            @Override // this means that we are replacing the old
            //method that is prebuilt with a new one.
            public void paintComponent(Graphics g) {
                super.paintComponent(g); //calls the old paintComponent method
                draw(g);//calls the draw method
            }
        };
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton(); setLocationRelativeTo(null)
        ;
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAInstructions = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        panDraw.setMaximumSize(new java.awt.Dimension(1920, 1080));
        panDraw.setMinimumSize(new java.awt.Dimension(1920, 1080));
        panDraw.setPreferredSize(new java.awt.Dimension(1920, 1080));

        lblTitle.setFont(new java.awt.Font("Pixelify Sans", 1, 120)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 51, 0));
        lblTitle.setText("STRUCTURED CHAOS");
        lblTitle.setMaximumSize(new java.awt.Dimension(330, 60));
        lblTitle.setMinimumSize(new java.awt.Dimension(330, 60));
        lblTitle.setPreferredSize(new java.awt.Dimension(960, 60));

        btnBack.setBackground(new java.awt.Color(255, 51, 0));
        btnBack.setFont(new java.awt.Font("Pixelify Sans", 1, 60)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtAInstructions.setBackground(new java.awt.Color(0, 0, 0));
        txtAInstructions.setColumns(20);
        txtAInstructions.setFont(new java.awt.Font("Pixelify Sans", 1, 24)); // NOI18N
        txtAInstructions.setForeground(new java.awt.Color(255, 51, 51));
        txtAInstructions.setRows(5);
        txtAInstructions.setText("1. Movement:\n   - Use the WASD or the ARROW keys to navigate your player through the level. \n   Press the W, UP ARROW, or Space key to make your player jump. You have the \n   ability to jump twice consecutively before landing.\n\n2. Objective:\n   - Collect all the coins scattered throughout the level and reach the end of \n   the level. Once all coins are collected, a door will open. Successfully reach the door\n   to display the winning screen, which will display your calculated score.\n \n3. Obstacles:\n   - Avoid spikes and moving obstacles, as they will instantly kill your player. Killing the\n   player will cause the player position to reset back to the start, and it will also\n   reset the collected coins back to 0.\n\n4. Lives:\n   - You start with 3 lives. Losing a life occurs when your player is hit by a spike or \n  moving obstacle.\n\n5. Game Over:\n   - If you run out of lives, the game ends and the game over screen will be displayed. \n   Try to complete each level with the highest number of lives possible. You will be \n   given a score upon completion of the level. Score is calculated\n   based on time and lives.\n\n6. Other:\n - Press the (ESC) key to pause the game.  Press the (H) key to show hitboxes.");
        txtAInstructions.setBorder(null);
        txtAInstructions.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAInstructions.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAInstructions.setFocusable(false);
        jScrollPane1.setViewportView(txtAInstructions);

        javax.swing.GroupLayout panDrawLayout = new javax.swing.GroupLayout(panDraw);
        panDraw.setLayout(panDrawLayout);
        panDrawLayout.setHorizontalGroup(
            panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDrawLayout.createSequentialGroup()
                .addGroup(panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDrawLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDrawLayout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDrawLayout.createSequentialGroup()
                        .addGap(533, 533, 533)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        panDrawLayout.setVerticalGroup(
            panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDrawLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        music.stop();
        frmMainMenu screen = new frmMainMenu();
        screen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    public void draw (Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        
        //BKGD
        g2.setColor(Color.BLACK);
        g2.fillRect(0, 0, 1920, 1080);
          
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInstructions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panDraw;
    private javax.swing.JTextArea txtAInstructions;
    // End of variables declaration//GEN-END:variables
}
