/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalprogrammingproject;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;

/**
 * Author: Abiishan and Munsif
 * Date: Jan. 24, 2023 
 * Project Name: frmLevelSelector.java
 * Description: Creating a level selector so that the user can choose whether they want to play level one or two.
 */

public class frmLevelSelector extends javax.swing.JFrame {
    
   // Sound Effect Variables 

    public Clip music; // Represents the audio clip for background music
    public long songTime = 0; // Represents the current time position in the music playback
    
    /**
     * Creates new form frmMainMenu
     */
    public frmLevelSelector() {
        initComponents(); // Initializes the components of the form
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Sets the frame to be maximized
        loadMusic(); // Loads and initializes the background music

        music.setMicrosecondPosition(songTime); // Sets the music to start at the specified time position
        music.loop(-1); // Loops the background music indefinitely
    }
    
    // Loads the background music from a file
    public void loadMusic() {
        // LOADING SOUND EFFECTS
        // Source: https://opengameart.org/content/platformer-game-music-pack

        try {
            // Load the audio file into an AudioInputStream
            AudioInputStream song = AudioSystem.getAudioInputStream(new File("introMusic.wav"));

            // Initialize the music clip
            music = AudioSystem.getClip();
            music.loop(0); // This will loop forever once played
            music.open(song);

        } catch (Exception e) {
            System.out.println(e + "Song file not found");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDraw = new javax.swing.JPanel(){

            //paintComponent happens on object creation and when
            //any changes occur to the frame (size change, new objects added.
                // etc.)
            @Override // this means that we are replacing the old
            //method that is prebuilt with a new one.
            public void paintComponent(Graphics g) {
                super.paintComponent(g); //calls the old paintComponent method
                draw(g);//calls the draw method
            }
        };
        lblTitle = new javax.swing.JLabel();
        btnLevel2 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton(); setLocationRelativeTo(null)
        ;
        btnLevel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        panDraw.setMaximumSize(new java.awt.Dimension(1920, 1080));
        panDraw.setMinimumSize(new java.awt.Dimension(1920, 1080));
        panDraw.setPreferredSize(new java.awt.Dimension(1920, 1080));

        lblTitle.setFont(new java.awt.Font("Pixelify Sans", 1, 120)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 51, 0));
        lblTitle.setText("STRUCTURED CHAOS");
        lblTitle.setMaximumSize(new java.awt.Dimension(330, 60));
        lblTitle.setMinimumSize(new java.awt.Dimension(330, 60));
        lblTitle.setPreferredSize(new java.awt.Dimension(960, 60));

        btnLevel2.setBackground(new java.awt.Color(255, 51, 0));
        btnLevel2.setFont(new java.awt.Font("Pixelify Sans", 1, 60)); // NOI18N
        btnLevel2.setForeground(new java.awt.Color(255, 255, 255));
        btnLevel2.setText("LEVEL 2");
        btnLevel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLevel2.setBorderPainted(false);
        btnLevel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevel2ActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 51, 0));
        btnBack.setFont(new java.awt.Font("Pixelify Sans", 1, 60)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnLevel1.setBackground(new java.awt.Color(255, 51, 0));
        btnLevel1.setFont(new java.awt.Font("Pixelify Sans", 1, 60)); // NOI18N
        btnLevel1.setForeground(new java.awt.Color(255, 255, 255));
        btnLevel1.setText("LEVEL 1");
        btnLevel1.setBorder(null);
        btnLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDrawLayout = new javax.swing.GroupLayout(panDraw);
        panDraw.setLayout(panDrawLayout);
        panDrawLayout.setHorizontalGroup(
            panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDrawLayout.createSequentialGroup()
                .addGroup(panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDrawLayout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addGroup(panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLevel2, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panDrawLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        panDrawLayout.setVerticalGroup(
            panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDrawLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(btnLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnLevel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevel1ActionPerformed
        music.stop();
        frmLevel1 screen1 = new frmLevel1();
        screen1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLevel1ActionPerformed

    private void btnLevel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevel2ActionPerformed
        music.stop();
        frmLevel2 screen2 = new frmLevel2();
        screen2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLevel2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        music.stop();
        frmMainMenu screen3 = new frmMainMenu();
        screen3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    public void draw (Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        
        //BKGD
        g2.setColor(Color.BLACK);
        g2.fillRect(0, 0, 1920, 1080);

          
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLevelSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLevelSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLevelSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLevelSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLevelSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLevel1;
    private javax.swing.JButton btnLevel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panDraw;
    // End of variables declaration//GEN-END:variables
}
