/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalprogrammingproject;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;

/**
 * Author: Abiishan and Munsif
 * Date: Jan. 24, 2023 
 * Project Name: frmMainMenu.java
 * Description: Creating a Main Menu for the game, Structured Chaos.
 */

public class frmMainMenu extends javax.swing.JFrame {
    
   // Sound Effect Variables 

    public Clip music; // Represents the audio clip for background music
    public long songTime = 0; // Represents the current time position in the music playback

    /**
     * Creates new form frmMainMenu
     */
    
    public frmMainMenu() {
        initComponents(); // Initializes the components of the form
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Sets the frame to be maximized
        loadMusic(); // Loads and initializes the background music

        music.setMicrosecondPosition(songTime); // Sets the music to start at the specified time position
        music.loop(-1); // Loops the background music indefinitely
    }

    // Loads the background music from a file
    public void loadMusic() {
        // LOADING SOUND EFFECTS
        // Source: https://opengameart.org/content/platformer-game-music-pack

        try {
            // Load the audio file into an AudioInputStream
            AudioInputStream song = AudioSystem.getAudioInputStream(new File("introMusic.wav"));

            // Initialize the music clip
            music = AudioSystem.getClip();
            music.loop(0); // This will loop forever once played
            music.open(song);

        } catch (Exception e) {
            System.out.println(e + "Song file not found");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDraw = new javax.swing.JPanel(){

            //paintComponent happens on object creation and when
            //any changes occur to the frame (size change, new objects added.
                // etc.)
            @Override // this means that we are replacing the old
            //method that is prebuilt with a new one.
            public void paintComponent(Graphics g) {
                super.paintComponent(g); //calls the old paintComponent method
                draw(g);//calls the draw method
            }
        };
        lblTitle = new javax.swing.JLabel();
        btnInstructions = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton(); setLocationRelativeTo(null)
        ;
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        panDraw.setMaximumSize(new java.awt.Dimension(1920, 1080));
        panDraw.setMinimumSize(new java.awt.Dimension(1920, 1080));
        panDraw.setPreferredSize(new java.awt.Dimension(1920, 1080));

        lblTitle.setFont(new java.awt.Font("Pixelify Sans", 1, 120)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 51, 0));
        lblTitle.setText("STRUCTURED CHAOS");
        lblTitle.setMaximumSize(new java.awt.Dimension(330, 60));
        lblTitle.setMinimumSize(new java.awt.Dimension(330, 60));
        lblTitle.setPreferredSize(new java.awt.Dimension(960, 60));

        btnInstructions.setBackground(new java.awt.Color(255, 51, 0));
        btnInstructions.setFont(new java.awt.Font("Pixelify Sans", 1, 60)); // NOI18N
        btnInstructions.setForeground(new java.awt.Color(255, 255, 255));
        btnInstructions.setText("INSTRUCTIONS");
        btnInstructions.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnInstructions.setBorderPainted(false);
        btnInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructionsActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(255, 51, 0));
        btnQuit.setFont(new java.awt.Font("Pixelify Sans", 1, 60)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("QUIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnPlay.setBackground(new java.awt.Color(255, 51, 0));
        btnPlay.setFont(new java.awt.Font("Pixelify Sans", 1, 60)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("PLAY");
        btnPlay.setBorder(null);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDrawLayout = new javax.swing.GroupLayout(panDraw);
        panDraw.setLayout(panDrawLayout);
        panDrawLayout.setHorizontalGroup(
            panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDrawLayout.createSequentialGroup()
                .addGroup(panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDrawLayout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addGroup(panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panDrawLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        panDrawLayout.setVerticalGroup(
            panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDrawLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        music.stop(); // Stops the background music
        frmLevelSelector screen1 = new frmLevelSelector(); // Creates a new level selector screen
        screen1.setVisible(true); // Sets the new screen to be visible
        this.dispose(); // Closes the current jFrame
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructionsActionPerformed
        music.stop();
        frmInstructions screen2 = new frmInstructions();
        screen2.setVisible(true);
        this.dispose();    }//GEN-LAST:event_btnInstructionsActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        this.dispose(); // Closes the current jFrame and ends the program
    }//GEN-LAST:event_btnQuitActionPerformed

    // Custom drawing method for the JPanel (panDraw)
    public void draw(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;

        // BKGD
        g2.setColor(Color.BLACK);
        g2.fillRect(0, 0, 1920, 1080); // Fills the background with a black color
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panDraw;
    // End of variables declaration//GEN-END:variables
}
